### Register user
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "username": "stanlee",
  "name": "Stan Lee",
  "email": "stan@lee.com",
  "password": "stanlee123"
}

### Register user with prohibited username
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "username": "admin",
  "name": "Admin User",
  "email": "admin@admin.com",
  "password": "admin"
}

### Login user
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "tony@stark.co",
  "password": "ironman0"
}

### Logout user
POST http://localhost:3000/auth/logout
Authorization: Bearer token

### Get authenticated user profile
GET http://localhost:3000/auth/profile
Authorization: Bearer token
